### ISSUE TITLE
[studio] Conformance does not shown for packages without tags

### ISSUE THREAD

**Issue by IKatsuba** [commonalityco/commonality#201] opened 2024-01-05 11:44 UTC
Just package with tags has the Conformance data

<img width="1286" alt="image" src="https://github.com/commonalityco/commonality/assets/10637135/591571f8-01c7-44c8-be10-c01c162f2394">

**Comment by alec-chernicki** [comment] 2024-01-05 20:41
It looks like there's a bug in changesets where devDependencies of a package aren't bumped unless they're explicitly defined in a changeset. 

I've released a patch version of `commonality` that includes a fix for this and am tracking the root cause of the issue in: https://github.com/changesets/changesets/pull/1159

**Closed by alec-chernicki** 2024-01-05 20:41 UTC
